# Generated by Django 5.2.9 on 2025-12-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
    ]
