# Generated by Django 5.2.9 on 2025-12-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_collection_description_collection_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='home_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/collections/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='home_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_look_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_new_arrivals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_shop_look',
            field=models.BooleanField(default=False),
        ),
    ]
