# Generated by Django 5.2.9 on 2025-12-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_collection_home_card_image_collection_home_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='home_card_image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price_inr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_arrival_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_look_order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_in_new_arrivals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_in_shop_look',
        ),
        migrations.AddField(
            model_name='collection',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/cards/'),
        ),
    ]
