# Generated by Django 5.2.9 on 2025-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_collection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='LOOKBOOK', max_length=80)),
                ('kicker', models.CharField(blank=True, default='2025 COLLECTION', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='lookbook/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='lookbook/')),
                ('cta_text', models.CharField(blank=True, default='SHOP ALL JEWELRY', max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='Example: /catalog/products/ or /catalog/collections/gold/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
