# Generated by Django 5.2.9 on 2025-12-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_lookbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('grid6', 'Grid (6 images)'), ('split2', 'Split (2 large images)'), ('media_products_left', 'Media Left + 4 Products Right'), ('media_products_right', '4 Products Left + Media Right'), ('quote_media_products', 'Quote + Media + 4 Products')], default='grid6', max_length=40)),
                ('quote_text', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=80)),
                ('quote_role', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='cta_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/hero/'),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/hero/'),
        ),
        migrations.CreateModel(
            name='LookbookSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('product', 'Product')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lookbook/sections/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('old_price_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slot', models.CharField(default='a', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.lookbooksection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
