# Generated by Django 5.2.9 on 2025-12-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_lookbooksection_alter_lookbook_cta_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbooksection',
            name='media_image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/sections/media/'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='media_side',
            field=models.CharField(choices=[('left', 'Media Left'), ('right', 'Media Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='old_price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='old_price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='old_price_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='old_price_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='product_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_p1', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='product_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_p2', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='product_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_p3', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='product_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_p4', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_left_caption',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_left_image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/sections/split/'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_left_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_split_left', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_right_caption',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_right_image',
            field=models.ImageField(blank=True, null=True, upload_to='lookbook/sections/split/'),
        ),
        migrations.AddField(
            model_name='lookbooksection',
            name='split_right_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lb_split_right', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='lookbooksection',
            name='layout',
            field=models.CharField(choices=[('grid6', 'Grid (6 images)'), ('split2', '2 Large Images'), ('media_products', 'Media + 4 Products'), ('quote_media_products', 'Quote + Media + 4 Products')], default='grid6', max_length=40),
        ),
        migrations.CreateModel(
            name='LookbookGridItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lookbook/sections/grid/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_items', to='catalog.lookbooksection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='LookbookSectionItem',
        ),
    ]
