# Generated by Django 5.2.9 on 2025-12-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_contactfaq_contactmessage_storelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary (Product)'), ('hover', 'Hover (Model Wearing)'), ('gallery', 'Gallery (Extra)')], db_index=True, default='gallery', max_length=20),
        ),
    ]
