# Generated by Django 5.2.9 on 2025-12-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productimage_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTheLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SHOP THE LOOK', max_length=80)),
                ('more_text', models.CharField(blank=True, default='More looks', max_length=40)),
                ('more_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='look/home/')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopTheLookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, help_text='Left % (0-100)', max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, help_text='Top % (0-100)', max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.shopthelook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
