# Generated by Django 5.2.2 on 2026-06-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_description_productfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage (%)'), ('flat', 'Flat Amount (INR)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Max cap for percentage coupons', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited uses')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_type', models.CharField(choices=[('ring', 'Ring Size Guide'), ('bangle', 'Bangle Size Guide'), ('bracelet', 'Bracelet Size Guide'), ('necklace', 'Necklace Length Guide'), ('earring', 'Earring Size Guide')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True, help_text='HTML or plain text guide content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='size_guides/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/hero/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='How to clean and store this jewelry'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.CharField(blank=True, choices=[('', 'None'), ('bis', 'BIS Hallmark'), ('igi', 'IGI Certified'), ('gia', 'GIA Certified'), ('igl', 'IGL Certified'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('unisex', 'Unisex'), ('kids', 'Kids')], db_index=True, default='women', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('rose_gold', 'Rose Gold'), ('platinum', 'Platinum'), ('brass', 'Brass'), ('mixed', 'Mixed Metal'), ('other', 'Other')], db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_purity',
            field=models.CharField(blank=True, help_text='e.g. 18K, 22K, 925 Sterling', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('daily', 'Daily Wear'), ('wedding', 'Wedding'), ('party', 'Party'), ('festival', 'Festival'), ('office', 'Office'), ('gifting', 'Gifting')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Unique product code / SKU', max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_type',
            field=models.CharField(blank=True, choices=[('none', 'No Stone'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('pearl', 'Pearl'), ('coral', 'Coral'), ('turquoise', 'Turquoise'), ('amethyst', 'Amethyst'), ('cubic_zirconia', 'Cubic Zirconia'), ('other', 'Other')], max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_weight_ct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Stone weight in carats', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='catalog.product')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('session_key', 'product')},
            },
        ),
    ]
