# Generated by Django 5.2.16 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_categories_and_journal_seeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_variant_gid',
            field=models.CharField(blank=True, default='', help_text='Shopify ProductVariant GID used for hosted checkout', max_length=120),
        ),
    ]
