# Generated by Django 5.2.16 on 2026-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_hide_gold_collection_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_product_gid',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, help_text='Available stock; pushed to Shopify on save'),
        ),
    ]
