# Generated by Django 5.2.16 on 2026-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_shopify_product_gid_product_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tryon_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tryon_image',
            field=models.ImageField(blank=True, help_text='Transparent PNG of the jewellery piece (front view) used for AR try-on', null=True, upload_to='tryon/'),
        ),
        migrations.AddField(
            model_name='product',
            name='tryon_type',
            field=models.CharField(blank=True, choices=[('ring', 'Ring'), ('necklace', 'Chain / Necklace'), ('bangle', 'Bangle / Bracelet')], max_length=20),
        ),
    ]
