# Generated by Django 5.2.9 on 2025-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
