# Generated by Django 5.2.2 on 2026-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_note_order_stripe_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
