# Generated by Django 5.2.16 on 2026-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_code_order_discount_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopify_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_order_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
